//! `hydra init` — scaffold a complete, ready-to-run `hydra.toml`.
//!
//! Unlike copying the sample config (which ships placeholder secrets), this
//! generates fresh, unique key material:
//!
//! * `master_secret` (32 B) + `server_salt` (16 B) — the keyed epoch pool secret,
//! * an X25519 keypair — the REALITY `privateKey` / `publicKey` (`pbk`),
//! * a random 8-byte `short_id`,
//!
//! and writes them alongside a curated default SNI pool and Cloudflare coherence
//! CIDRs. The same file works on the server (uses `privateKey`) and the client
//! (uses `public_key` + `short_ids`); distribute it out of band (REALITY.md §12).

use std::path::Path;

use base64::Engine as _;
use clap::Args;
use reality_tls::auth::generate_keypair;

use crate::error::CliError;

#[derive(Args, Debug)]
pub struct InitArgs {
    /// Where to write the generated config.
    #[arg(short, long, value_name = "PATH", default_value = "hydra.toml")]
    pub output: String,

    /// Overwrite an existing file.
    #[arg(long)]
    pub force: bool,

    /// The single CDN edge `dest` (host:port) probes fall back to.
    #[arg(long, value_name = "HOST:PORT", default_value = "www.cloudflare.com:443")]
    pub dest: String,

    /// Number of SNIs live per epoch.
    #[arg(long, value_name = "N", default_value_t = 6)]
    pub active_k: usize,

    /// Epoch length (integer + h/m/s).
    #[arg(long, value_name = "DUR", default_value = "6h")]
    pub epoch_len: String,

    /// Print the generated config to stdout instead of writing a file.
    #[arg(long)]
    pub stdout: bool,
}

/// A curated default pool: real high-reputation domains on Cloudflare. Operators
/// should replace these with domains genuinely fronted by *their* CDN (REALITY.md §12).
const DEFAULT_POOL: &[(&str, f64)] = &[
    ("www.cloudflare.com", 8.0),
    ("www.digitalocean.com", 6.0),
    ("www.medium.com", 6.0),
    ("www.discord.com", 7.0),
    ("play.google.com", 6.5),
    ("www.udemy.com", 5.0),
    ("www.canva.com", 6.0),
    ("www.upwork.com", 5.0),
    ("www.fiverr.com", 4.5),
    ("www.gitlab.com", 5.0),
    ("www.zendesk.com", 4.0),
    ("www.hubspot.com", 4.0),
];

/// Default Cloudflare coherence CIDRs (Traps 2 & 3, REALITY.md §4).
const DEFAULT_CIDRS: &[&str] = &[
    "104.16.0.0/13",
    "172.64.0.0/13",
    "173.245.48.0/20",
    "141.101.64.0/18",
    "108.162.192.0/18",
    "190.93.240.0/20",
    "188.114.96.0/20",
    "162.158.0.0/15",
    "131.0.72.0/22",
];

fn b64(bytes: &[u8]) -> String {
    base64::engine::general_purpose::STANDARD.encode(bytes)
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// Build the config text (pure; no I/O) so it is unit-testable.
pub fn render_config(args: &InitArgs) -> (String, String, String) {
    // 32 random bytes for the master secret (an X25519 private key is exactly 32
    // uniformly-random bytes from the vetted OsRng — reuse it rather than pull in
    // another RNG crate).
    let (master_secret, _) = generate_keypair();
    let (salt_src, _) = generate_keypair();
    let server_salt = &salt_src[..16];
    let (sid_src, _) = generate_keypair();
    let short_id = &sid_src[..8];

    let (private_key, public_key) = generate_keypair();
    let pbk = b64(&public_key);
    let sid = hex(short_id);

    let mut pool = String::new();
    for (sni, weight) in DEFAULT_POOL {
        pool.push_str(&format!("[[pool]]\nsni    = \"{sni}\"\nweight = {weight:.1}\n\n"));
    }

    let mut cidrs = String::new();
    for cidr in DEFAULT_CIDRS {
        cidrs.push_str(&format!("    \"{cidr}\",\n"));
    }

    let toml = format!(
        "# hydra.toml — generated by `hydra init`.\n\
         # Secrets below are UNIQUE to this deployment. Keep this file private and\n\
         # distribute it to clients out of band (REALITY.md §12).\n\
         master_secret = \"base64:{ms}\"   # 32 B — rotate on suspected leak\n\
         server_salt   = \"base64:{ss}\"   # 16 B — per-deployment\n\
         pool_format   = \"hydra-pool-v1\"\n\
         epoch_len     = \"{epoch_len}\"\n\
         active_k      = {active_k}\n\
         \n\
         # The single CDN edge probes fall back to. Every pool SNI MUST be a real\n\
         # domain served by this CDN (REALITY.md §5.3).\n\
         dest            = \"{dest}\"\n\
         coherence_cidrs = [\n{cidrs}]\n\
         \n\
         # ── Self-tunnel (no Xray): the Rust `hydra server` exit node ──\n\
         # Uncomment and point at YOUR VPS to use the built-in tunnel instead of a\n\
         # stock Xray REALITY server. `server_addr` is where the client dials; if\n\
         # left unset the client falls back to `dest`. `cert_pin` is printed by\n\
         # `hydra server` on first run (SHA-256 of its self-signed cert).\n\
         # server_addr = \"YOUR.VPS.IP:443\"\n\
         # cert_pin    = \"base64:...\"   # from `hydra server` output\n\
         \n\
         # REALITY handshake keys (this section is what `keygen` produces).\n\
         [reality]\n\
         private_key = \"base64:{pk}\"   # SERVER only — omit on client copies\n\
         public_key  = \"base64:{pbk}\"  # client pbk\n\
         short_ids   = [\"{sid}\"]\n\
         fingerprint = \"chrome\"\n\
         \n\
         # ── SNI pool: replace with domains genuinely fronted by YOUR CDN ──\n\
         {pool}",
        ms = b64(&master_secret),
        ss = b64(server_salt),
        pk = b64(&private_key),
        epoch_len = args.epoch_len,
        active_k = args.active_k,
        dest = args.dest,
    );

    (toml, pbk, sid)
}

pub fn run(args: &InitArgs) -> Result<String, CliError> {
    let (toml, pbk, sid) = render_config(args);

    if args.stdout {
        return Ok(toml);
    }

    let path = Path::new(&args.output);
    if path.exists() && !args.force {
        return Err(CliError::AlreadyExists(args.output.clone()));
    }
    std::fs::write(path, &toml).map_err(|source| CliError::Io {
        path: args.output.clone(),
        source,
    })?;

    Ok(format!(
        "Wrote {}\n\n\
         Share these client-side values (they are safe to hand to clients):\n\
         \x20 pbk (public_key): {pbk}\n\
         \x20 sid (short_id):   {sid}\n\n\
         Next — pick ONE server path:\n\
         \x20 A) Self-tunnel (no Xray), the built-in Rust exit node:\n\
         \x20    server (VPS): hydra server -c {out} --listen 0.0.0.0:443   # prints cert_pin\n\
         \x20    client:       set server_addr + cert_pin in {out}, then\n\
         \x20                  hydra serve -c {out} --listen 127.0.0.1:1080\n\
         \x20 B) Stock Xray REALITY server:\n\
         \x20    server:  hydra server-names -c {out} --format xray > reality-inbound.json\n\
         \x20    client:  hydra serve -c {out} --listen 127.0.0.1:1080",
        args.output,
        out = args.output,
    ))
}
